### PR TITLE
Fix potential issue of extract_string().

### LINKED ISSUE #31: unsoundness in `extract_string` function
```rust
pub fn extract_string(raw: &[u8], off: usize) -> Option<&str> {
    let mut end = off;

    if off >= raw.len() {
        return None;
    }
    while raw[end] != 0 {
        end += 1;
    }
    let blk = raw[off..end].as_ptr() as *mut u8;
    let r = unsafe { String::from_raw_parts(blk, end - off, end - off) };
    let ret = Some(unsafe { &*(r.as_str() as *const str) }); // eliminate lifetime
    r.into_bytes().leak();
    ret
}
```
The function's implementation seems broken. First off, it should document safety invariants upheld in `unsafe` blocks with [`SAFETY` comments](https://std-dev-guide.rust-lang.org/documentation/safety-comments.html#safety-comments). For `String::from_raw_parts`, these read:
```
    /// # Safety
    ///
    /// This is highly unsafe, due to the number of invariants that aren't
    /// checked:
    ///
    /// * The memory at `buf` needs to have been previously allocated by the
    ///   same allocator the standard library uses, with a required alignment of exactly 1.
    /// * `length` needs to be less than or equal to `capacity`.
    /// * `capacity` needs to be the correct value.
    /// * The first `length` bytes at `buf` need to be valid UTF-8.
    ///
    /// Violating these may cause problems like corrupting the allocator's
    /// internal data structures. For example, it is normally **not** safe to
    /// build a `String` from a pointer to a C `char` array containing UTF-8
    /// _unless_ you are certain that array was originally allocated by the
    /// Rust standard library's allocator.
    ///
    /// The ownership of `buf` is effectively transferred to the
    /// `String` which may then deallocate, reallocate or change the
    /// contents of memory pointed to by the pointer at will. Ensure
    /// that nothing else uses the pointer after calling this
    /// function.
```

Evaluating these:
- The memory at `buf` needs to have been previously allocated by the same allocator the standard library uses, with a required alignment of exactly 1.
  - this is with almost 100% certainty violated: the memory has not been allocated with the standard allocator; it's also not communicated to callers in any way. So at best this function is unsound and a ticking time bomb, but most likely plain undefined behavior.
- `capacity` needs to be the correct value
  - Questionable; could be the case but unlikely. Again, unsoundness at the very least as it's certainly not ensured/enforced anywhere.
- The first `length` bytes at `buf` need to be valid UTF-8
  - not ensured anywhere. Again, callers may randomly uphold this invariant, but in all likelihood it's violated in all but a few places that got lucky. It's also not communicated to callers in any way.

### PR DESCRIPTION
**Pull request by ThinkerYzu1**
Fixes #31. We use CStr instead to fix these concerns.

Signed-off-by: Kui-Feng Lee <kuifeng@fb.com>

### CODE REVIEW

File: src/tools.rs [hunk 1]
```diff
@@ -100,14 +101,16 @@ pub fn extract_string(raw: &[u8], off: usize) -> Option<&str> {
...
-    let ret = Some(unsafe { &*(r.as_str() as *const str) }); // eliminate lifetime
-    r.into_bytes().leak();
-    ret
+    if end >= raw.len() {
+        return None;
+    }
+    end += 1;
+    let blk = raw[off..end].as_ptr() as *const i8;
+    let r = unsafe { CStr::from_ptr(blk) };
+    r.to_str().ok()
```
Comment (danielocfb) [inline src/tools.rs:113]: I think this can be shortened to:
```rust
pub fn extract_string(raw: &[u8], off: usize) -> Option<&str> {
    if off >= raw.len() {
        return None;
    }
    CStr::from_bytes_with_nul(&raw[off..]).ok()?.to_str().ok()
}
```
Right?

**Review by danielocfb — COMMENTED** [review]
The approach seems much saner now, thanks! I left one comment that I think we should address.

**Comment by danielocfb** [comment]
Can you please also fix the spelling mistake in the subject?

FYI, If you want to automatically close an issue when a change is merged, you can annotate it with
```
Fixes: #31
```

See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.

File: src/tools.rs (hunk 1 above)
Comment (danielocfb) [reply src/tools.rs:113]: Actually the NUL byte detection is still necessary, because `from_bytes_with_nul` assumes no interior NUL bytes. But we don't have to use `unsafe` at least and it's shorter still.

**Comment by ThinkerYzu1** [comment]
> 

Thank you! Good to know.

File: src/tools.rs (hunk 1 above)
Comment (ThinkerYzu1) [reply src/tools.rs:113]: Got it. `from_bytes_with_nul()` is better.

**Review by danielocfb — APPROVED** [review]
Looks good to me, thanks!

**Comment by ThinkerYzu1** [comment]
Thanks!
